<HTML>
<head>
<script language="JavaScript">
function checkForm()
{
   var structId, chainId;
   with(window.document.proteinform)
   {
      structId = pdbId;
      chainId = chain;
   }

      return true;
   }
}

function trim(str)
{
   return str.replace(/^\s+|\s+$/g,'');
}
</script>
</head>
<?php
	include("components/environment.php");
	include("components/menu.php");
	include("components/sidemenu.php");
	
	PrintHeader("Compare Performance of Domain Assignment Algorithms & Generate a Consensus");
	
	print '
	  <table width="95%"  border="0" cellspacing="0" cellpadding="0">
		<tr align="left">
		  <td valign="top" width="242">';
		  PrintSideMenuBox("Method Performance",GetSideMenuItems("Domain Assignments","Download Domain Assignments",null,null));
		  print '
		  </td>
		  <td valign="top" align="left"><div id="textheading">Download Domain Assignment Data</div>
			<br>
			  <div id="textinfo">
			  <p>This tool provides the functionality to download the assignments generated by the domain assignment algorithms, for a set of proteins. This is comprised of a CSV file. Note this is just the assignments from each algorithm, not the consensus that is generated from them<BR><BR>
<b>NB: Please separate PDB Ids by a comma (For example: 1HTB,2Q14,9XIM)</b>


		  <FORM name="domainform" action="assignmentDataDump.php" method="post">


			<table width=70% bgcolor="#6887C4">
			<TR>
				<TD>CATH</TD>
				<TD><input type="checkbox" checked="yes" name="CATH" value="true"></TD>
				<TD>SCOP</TD>
				<TD><input type="checkbox" checked="yes" name="SCOP" value="true"></TD>
				<TD>pdp</TD>
				<TD><input type="checkbox" checked="yes" name="pdp" value="true"></TD>
			</TR>
			<TR>
				<TD>dp</TD>
				<TD><input type="checkbox" checked="yes" name="dp" value="true"></TD>
				<TD>DHcL</TD>
				<TD><input type="checkbox" checked="yes" name="DHcL" value="true"></TD>
				<TD>DDomain</TD>
				<TD><input type="checkbox" checked="yes" name="DDomain" value="true"></TD>
			</TR>
			<TR>
				<TD>PUU</TD>
				<TD><input type="checkbox" checked="yes" name="PUU" value="true"></TD>
				<TD>NCBI</TD>
				<TD><input type="checkbox" checked="yes" name="NCBI" value="true"></TD>
				<TD>Dodis</TD>
				<TD><input type="checkbox" checked="yes" name="Dodis" value="true"></TD>
			</TR>
			<TR>
			<TD COLSPAN=6>
				<textarea rows="5" cols="86" name="pdbIdList" wrap="soft"></textarea>
			</TD>
			</TR>
			<TR>
			<TD COLSPAN=6>
				<input type="submit" value="Download" onClick="return checkForm();">
			</TD>
			</TR>

			</table>
		  </FORM>
		
		
</div>



		</td>
		</tr>
	  </table>
	<br>
	<br>
	<br>';	
	
	PrintFooter();
?>
